name: Build & Push Docker Image

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Docker login for GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # 3. Build Docker image
      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}:latest .

      # 4. Push Docker image to GitHub Packages
      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}:latest