name: Auto Bump Maven Version from Tag

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on semantic version tags like v1.2.3

jobs:
  update-maven-version:
    runs-on: ubuntu-latest

    steps:
      - name: Check out main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
          persist-credentials: true

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Extract version from tag
        id: vars
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Update Maven version
        run: mvn -q versions:set -DnewVersion=$VERSION

      # 5. Commit and push changes
      - name: Commit updated version to main
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -A pom.xml
          # Only commit if there are changes
          if ! git diff --cached --quiet; then
            git commit -m "Bump Maven version to $VERSION"
            git push origin main
          else
            echo "No changes to commit"
          fi
